name: Reusable CI for java with maven

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version to use'
        required: true
        default: '17'
        type: string
      agent:
        description: 'The type of agent to run the job on'
        required: true
        default: 'ubuntu-24.04'
        type: string
permissions:
  checks: write
  contents: read
  pull-requests: write
  actions: read
  security-events: write
jobs:
  manual:
    runs-on: ${{ inputs.agent }}
    
      

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build package
        run: mvn clean package

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            **/target/surefire-reports/TEST-*.xml

      - name: Upload packaged jar files
        uses: actions/upload-artifact@v4
        with:
          name: spring-petclinic.jar
          path: '**/target/*.jar'
                      
